/*======================================================
* file: Game.java
* Author: Calum Lindsay
* Created: 06-10/2021
* Last Modified: 16-02/2022
* Notes: This is the main Game class for my sokoban
* implementation. The entry point for the program and 
* the game logic are contained in this class.
========================================================*/


/*
* Control Scheme:
* WASD/Arrow keys: move character
* R: reset the current level
* Enter: move to next level if level is complete
* Escape: exit the game
*/

package sokoban;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Game extends javax.swing.JFrame implements KeyListener {

    private boolean complete;
    private int dir;
    private int level;
    private String mapNames[];
    private HashMap<String,ImageIcon> imageHashMap;
    private Coord playerLoc;
    private JLabel myElements[][];
    private Map tmpMap;
    
    ImageIcon getImage(String filename)
    {
        if(imageHashMap.get(filename)==null)
        {
            //Check that the filename exists in the package
            var stream = getClass().getResourceAsStream(filename);
            if(stream == null)
                return null;

            try
            {
                imageHashMap.put(filename, new ImageIcon(ImageIO.read(stream)));
            }
            catch(IOException e)
            {
                e.printStackTrace();
                return null;
            }
        }
        
        return imageHashMap.get(filename);
    }
    
    public void drawMap()
    {
        for(int i = 0; i<tmpMap.getLength();i++)
        {
            for(int j=0;j<tmpMap.getBreadth();j++)
            {
                myElements[i][j].setIcon(getImage(tmpMap.getElement(j,i).getImgFilename()));
            }
        }
    }
    
    public void refreshWindowLayout()
    {
        //Reset and resize window and components as needed
        int length = tmpMap.getLength(), breadth = tmpMap.getBreadth();
        myElements = new JLabel[length][breadth];
        southPanel.setPreferredSize(new java.awt.Dimension(breadth*32+20, 20));
        this.setPreferredSize(new java.awt.Dimension(breadth*32+20,length*33+50));
        centrePanel.setLayout(new java.awt.GridLayout(length, breadth));
        pack();
        
        //Resize GridLayout
        centrePanel.removeAll();
        for(int i=0;i<length;i++)
        {
            for(int j=0;j<breadth;j++)
            {
                myElements[i][j] = new JLabel();
                centrePanel.add(myElements[i][j]);
            }
        }
    }
    
    //Game Constructor
    public Game() {
        this.tmpMap = new Map();
        imageHashMap = new HashMap<String, ImageIcon>();
        this.setResizable(false);
        //Initialise JFrame
        initComponents();
        //Initialise KeyListener
        this.addKeyListener(this);
        this.setFocusable(true);
        
        //Configure Window and grid layout
        this.setTitle("Sokoban");
        
        //Initialise Game state
        level = 0;
        
        mapNames = new String[8];
        for(int i=0;i<mapNames.length;i++)
        {
            mapNames[i] = "Map" + i + ".map";
        }
        
        if(!tmpMap.loadMap(mapNames[level]))
        {
            lbl_moves.setText("Error: unable to load map file!");
            complete = true;
        }
        else
        {
            refreshWindowLayout();

            tmpMap.findPlayer();

            drawMap();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        southPanel = new javax.swing.JPanel();
        lbl_moves = new javax.swing.JLabel();
        centrePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        southPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        southPanel.setPreferredSize(new java.awt.Dimension(400, 15));

        lbl_moves.setText("Controls: R - Reset Map, Enter - Next Map, WASD/Arrows - Movement");

        javax.swing.GroupLayout southPanelLayout = new javax.swing.GroupLayout(southPanel);
        southPanel.setLayout(southPanelLayout);
        southPanelLayout.setHorizontalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_moves, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        southPanelLayout.setVerticalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(southPanelLayout.createSequentialGroup()
                .addComponent(lbl_moves)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(southPanel, java.awt.BorderLayout.PAGE_END);

        centrePanel.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout centrePanelLayout = new javax.swing.GroupLayout(centrePanel);
        centrePanel.setLayout(centrePanelLayout);
        centrePanelLayout.setHorizontalGroup(
            centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        centrePanelLayout.setVerticalGroup(
            centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        getContentPane().add(centrePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if(!complete)
        {
            if(!tmpMap.checkForWin())
            {
                switch(e.getKeyCode())
                {
                    case KeyEvent.VK_W, KeyEvent.VK_UP:
                        lbl_moves.setText("Pressed Up");
                        tmpMap.movePlayer(1);
                        break;
                    case KeyEvent.VK_S, KeyEvent.VK_DOWN:
                        lbl_moves.setText("Pressed Down");
                        tmpMap.movePlayer(3);
                        break;
                    case KeyEvent.VK_A, KeyEvent.VK_LEFT:
                        lbl_moves.setText("Pressed Left");
                        tmpMap.movePlayer(4);
                        break;
                    case KeyEvent.VK_D, KeyEvent.VK_RIGHT:
                        lbl_moves.setText("Pressed Right");
                        tmpMap.movePlayer(2);
                        break;
                }
                if(tmpMap.checkForWin())
                {
                    if(level == mapNames.length-1)
                    {
                        complete = true;
                        lbl_moves.setText("Completed in " + tmpMap.getNumMoves() + " moves! | Game Over!!!");
                    }
                    else
                    {
                        lbl_moves.setText("Completed in " + tmpMap.getNumMoves() + " moves!");
                    }
                }
            }
            else if (e.getKeyCode()== KeyEvent.VK_ENTER)
            {
                //Load next map
                ++level;
                tmpMap.resetNoMoves();
                 if(!tmpMap.loadMap(mapNames[level]))
                {
                    lbl_moves.setText("Error: unable to load map file!");
                    complete = true;
                }
                else
                {
                    tmpMap.findPlayer();
                    refreshWindowLayout();
                    lbl_moves.setText("Level " + (level+1) + "/" + mapNames.length);
                }
            }   
        }
        if(e.getKeyCode() == KeyEvent.VK_R)
        {
            //Reload and reset the map
            complete = false;
            tmpMap.resetNoMoves();
            if(!tmpMap.loadMap(mapNames[level]))
            {
                lbl_moves.setText("Error: unable to load map file!");
                complete = true;
            }
            else
            {
                tmpMap.findPlayer();
            }
        }
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            this.dispose();
        }
        
        drawMap();
    }

    //Unused KeyListener Functions
    @Override
    public void keyTyped(KeyEvent e) {}
    @Override
    public void keyReleased(KeyEvent e) {}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centrePanel;
    private javax.swing.JLabel lbl_moves;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables
}
